map_file: "./example/maze-32-32-2.map"
scen_file: "./example/maze-32-32-2-random-2.scen"
plan_file: "./example/result.path"
num_of_agents: 50
show_grid: true
show_ag_idx: true
show_static: true
show_conf_ag: true
pixel_per_move: 5
moves: 5
delay: 0.08