exp_path: "/home/rdaneel/PBS_results_SOCS2023/final_trial"
time_limit: 60
time_gap: 15
figure_width: 10
figure_height: 10
set_title: true
set_legend: true
marker_size: 20
line_width: 4.0
marker_width: 4.0
text_size: 28
alpha: 1.0
set_shift: 0
variation: "none"  # "std": standard deviation or "ci": confidence interval
x_grid: false
y_grid: true

maps:
  - name: "random-32-32-20"
    label: Random
    scens:
      - random
    num_of_agents:
      - 200
      - 250
      - 300
      - 350
      - 400

  - name: "maze-32-32-2"
    label: Maze
    scens:
      - random
    num_of_agents:
      - 100
      - 150
      - 200
      - 250
      - 300

  - name: "room-32-32-4"
    label: Room
    scens:
      - random
    num_of_agents:
      - 100
      - 150
      - 200
      - 250
      - 300

  - name: "warehouse-10-20-10-2-1"
    label: Warehouse(M)
    scens:
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800
      - 1000

  - name: "warehouse-20-40-10-2-1"
    label: Warehouse(L)
    scens:
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800
      - 1000

  - name: "den520d"
    label: Game
    scens:
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800
      - 1000

solvers:
  - name: "PBS-MA"
    label: "PBS w/m"
    color: "deepskyblue"
    markerfacecolor: "white"
    marker: "o"
    zorder: 0

  # - name: "EECBS"
  #   label: "EECBS"
  #   color: "orange"
  #   marker: "d"
  #   zorder: 1

  # - name: "LNS"
  #   label: "MAPF-LNS2"
  #   color: "green"
  #   marker: "s"
  #   zorder: 2

  # - name: "LACAM"
  #   label: "LACAM"
  #   color: "gold"
  #   marker: "*"
  #   zorder: 2
  
  - name: "PBS2-PE-TR-IC-SR0"
    label: "GPBS(PE,TR,IC,SR)"
    color: "red"
    markerfacecolor: "white"
    marker: "^"
    zorder: 4
